#!/usr/bin/env python

from fiona import collection

with collection("karnataka_poi.shp", "r") as source:

    with collection(
            "test_write.geojson", "w",
            driver='GeoJSON', schema=source.schema, crs=source.crs
            ) as sink:
        for f in source:
            #f = f.encode('utf-8')
            print f
            sink.write(f)
